### ISSUE TITLE
Import error for FDM experiments by name through FDMExperiements.ipynb in Docker container

### ISSUE THREAD

**Issue by sandbornm** [symbench/symbench-athens-client#111]
Import experiments by name (e.g. `ExperimentOnTurnigyGraphene5000MAHQuadCopter`) is deprecated because of the parallelization efforts. This should be replaced with the function which retrieves available experiments:

Error:

<img width="883" alt="Screen Shot 2021-08-27 at 11 19 25 AM" src="https://user-images.githubusercontent.com/35283365/131159418-bb5a418c-a642-4ad7-b13a-84a670a21692.png">

Solution:

<img width="737" alt="Screen Shot 2021-08-27 at 11 33 30 AM" src="https://user-images.githubusercontent.com/35283365/131159856-ca5dfe68-52dc-487c-b46d-61fc945a2314.png">

**Comment by umesh-timalsina** [comment]
The testbench library which has been moved to google drive available at the following [URL](https://drive.google.com/drive/u/1/folders/10EH32A41V20o1WhJTC7UQP0TPrKJY7th) is properly updated to use master branch functions.
